mod_metadata("name", "1 XP Towers By Goldenape")

jet_binary_replace("game_data/game_project/assets/towers/alchemist/data/alchemist.tower_blueprint", "alchemist.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/banana_farm/data/banana_farm.tower_blueprint", "banana_farm.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/bomb_shooter/data/bomb_shooter.tower_blueprint", "bomb_shooter.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/boomerang_monkey/data/boomerang_monkey.tower_blueprint", "boomerang_monkey.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/dart_monkey/data/dart_monkey.tower_blueprint", "dart_monkey.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/dartling_gunner/data/dartling_gunner.tower_blueprint", "dartling_gunner.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/druid_monkey/data/druid_monkey.tower_blueprint", "druid_monkey.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/engineer_monkey/data/engineer_monkey.tower_blueprint", "engineer_monkey.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/glue_gunner/data/glue_gunner.tower_blueprint", "glue_gunner.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/heli_pilot/data/heli_pilot.tower_blueprint", "heli_pilot.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/ice_monkey/data/ice_monkey.tower_blueprint", "ice_monkey.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/monkey_ace/data/monkey_ace.tower_blueprint", "monkey_ace.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/monkey_buccaneer/data/monkey_buccaneer.tower_blueprint", "monkey_buccaneer.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/monkey_sub/data/monkey_sub.tower_blueprint", "monkey_sub.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/monkey_village/data/monkey_village.tower_blueprint", "monkey_village.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/mortar_monkey/data/mortar_monkey.tower_blueprint", "mortar_monkey.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/ninja_monkey/data/ninja_monkey.tower_blueprint", "ninja_monkey.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/sniper_monkey/data/sniper_monkey.tower_blueprint", "sniper_monkey.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/spike_factory/data/spike_factory.tower_blueprint", "spike_factory.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/super_monkey/data/super_monkey.tower_blueprint", "super_monkey.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/tack_shooter/data/tack_shooter.tower_blueprint", "tack_shooter.tower_blueprint")
jet_binary_replace("game_data/game_project/assets/towers/wizard_monkey/data/wizard_monkey.tower_blueprint", "wizard_monkey.tower_blueprint")
